name: Oliver Thylmann
favicon: null
layout_spectrum: 0.03511996427550912
typography_spectrum: 0.7697155498899519
title: Oliver Thylmann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8320108482148498
  lightness: 0.9169711808208376
  saturation: 0.35585010680370033
  rhythmicContrast: 0.341446106787771
purpose: []
